### ISSUE TITLE
weak guide

### ISSUE THREAD

**Issue by hgfeaon** [gradle-guides/building-spring-boot-2-projects-with-gradle#12]
1. why this guide mention the un-necessary concepts like build-scan, is it a right thing to expose the build info to the public network when the gradle used in-house software development
2. the dependency with the bom example is very ugly

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #286](https://github.com/gradle/guides/issues/286) via [**ZenHub**](https://www.zenhub.com/)
