### ISSUE TITLE
dependency handling seems wrong

### ISSUE THREAD

**Issue by jnizet** [gradle-guides/building-spring-boot-2-projects-with-gradle#13]
First, the guide starts by adding this plugin:

    id 'io.spring.dependency-management' version '1.0.7.RELEASE'

and then says:

> Next we need to add the dependencies needed to compile and run our example as we are not using Spring’s dependency management plugin

which are completely contradictory.

The guide continues with

    implementation 'org.springframework.boot:spring-boot-dependencies:2.0.5.RELEASE'

which seems unnecessary, since that dependency is a BOM, and the spring boot plugin along with the spring dependency management plugin already imports this bom.

I think this guide should showcase the native BOM support in gradle, with a concrete example using the Spring Boot Dependencies BOM (which is probably the main reason why bom support exists in the first place). And it should thus

 - not use the plugin 'io.spring.dependency-management'
 - replace `implementation 'org.springframework.boot:spring-boot-dependencies:2.0.5.RELEASE'` by `implementation platform('org.springframework.boot:spring-boot-dependencies:2.0.5.RELEASE'))`

I came to this guide to confirm that this is the proper way to do (because the difference between platform and enforcePlatform is not so clear in the documentation), but was quite disappointed that this guide seems broken.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #288](https://github.com/gradle/guides/issues/288) via [**ZenHub**](https://www.zenhub.com/)
