### ISSUE TITLE
URL: https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import gives me a HTTP 404

### ISSUE THREAD

**Issue by taxdawg** [gradle-guides/building-spring-boot-2-projects-with-gradle#14]
reading document on this page 

https://guides.gradle.org/building-spring-boot-2-projects-with-gradle/
There is a section that has an information icon with this text 

If you’d like to read more about Gradle’s BOM support please visit this page.

Which directs me to this URL.
https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import

And my browser shows a Page Not Found message.. 

My expectation was that I would be led to a page that would enlighten me on gradle's BOM.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #304](https://github.com/gradle/guides/issues/304) via [**ZenHub**](https://www.zenhub.com/)
