### ISSUE TITLE
HelloGradleController code is not included in the guide

### ISSUE THREAD

**Issue by KajanM** [gradle-guides/building-spring-boot-2-projects-with-gradle#3]
https://guides.gradle.org/building-spring-boot-2-projects-with-gradle/#creating_a_hello_gradle_sample_application

> In the class above we create a new Spring Boot application and a HelloGradleController which returns Hello Gradle! when a GET request is processed on the root path of the application.

Please include the `HelloGradleController` code

**Comment by guylabs** [comment]
Hi @KajanM 

thanks for reporting this issue. Its already fixed on a branch and will be live asap.

**Comment by KajanM** [comment]
No problem.
That's great.
BTW thanks for the awesome work :)
