### ISSUE TITLE
dependency version related error

### ISSUE THREAD

**Issue by qiaojjun** [gradle-guides/building-spring-boot-2-projects-with-gradle#6]
when i step on follow the guide , i encountered the following error:
********************
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.springframework.boot:spring-boot-starter-web:.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
1 actionable task: 1 executed

During the build, one or more dependencies that were declared without a version failed to resolve:
    org.springframework.boot:spring-boot-starter-web:

Did you forget to apply the io.spring.dependency-management plugin to the gradle-spring-boot-project project?
**************************************
I fixed this by doing the following adjustment in the build.gradle:
implementation 'org.springframework.boot:spring-boot-dependencies:2.0.5.RELEASE'
changed to::::
implementation platform('org.springframework.boot:spring-boot-dependencies:2.0.5.RELEASE')

any further analysis ???

**Comment by linuxswords** [comment]
I stumbled upon the same error. I managed to complete the guide by:
- upgrading the build scan to version 2.0.2 as the error on my side suggested

` id 'com.gradle.build-scan' version '2.0.2'`

The next error I encountered was that I did not apply the plugin, so I added 
`apply plugin: 'io.spring.dependency-management'`
to `build.gradle`

OS: Ubuntu 18.04
Gradle Version 5.0.0

**Comment by shimachao** [comment]
> I stumbled upon the same error. I managed to complete the guide by:
> 
> * upgrading the build scan to version 2.0.2 as the error on my side suggested
> 
> ` id 'com.gradle.build-scan' version '2.0.2'`
> 
> The next error I encountered was that I did not apply the plugin, so I added
> `apply plugin: 'io.spring.dependency-management'`
> to `build.gradle`
> 
> OS: Ubuntu 18.04
> Gradle Version 5.0.0

Think you, it works.

OS:windows 10
Gradle: 5.0
Editor:vscode

**Comment by ocarlsen** [comment]
I had same problem.  You can fix by adding ":2.0.5.RELEASE" to all un-versioned dependencies.  Alternatively, to use BOM functionality, wrap the `spring-boot-dependencies` line with platform() like this:

    implementation platform('org.springframework.boot:spring-boot-dependencies:2.0.5.RELEASE')

**Comment by markserrano915** [comment]
I wanna document some of the issues I've found:

**Issue #1: Wrong build-scan version.**
```
What went wrong:
An exception occurred applying plugin request [id: 'com.gradle.build-scan', version: '1.16']
> Failed to apply plugin [id 'com.gradle.build-scan']
   > This version of Gradle requires version 2.0.2 of the build scan plugin or later.
     Please see https://gradle.com/scans/help/gradle-incompatible-plugin-version for more information.
```
**Solution:** 
Update the build-scan plugin to `2.0.2`
```
id 'com.gradle.build-scan' version '2.0.2'
```

**Issue #2: Wrong build-scan version.**
```
* What went wrong:
Plugin [id: 'io.spring.dependency-management'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
```
**Solution:**
Add this to plugins section: `id "io.spring.dependency-management" version "1.0.6.RELEASE"`

**Comment by PeterJakubik** [comment]
I think that build.gradle should use ```implementation platform```

I was able to compile it with gradle 5.2.1
```
implementation platform('org.springframework.boot:spring-boot-dependencies:2.0.5.RELEASE')
implementation 'org.springframework.boot:spring-boot-starter-web'
```

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #275](https://github.com/gradle/guides/issues/275) via [**ZenHub**](https://www.zenhub.com/)
